### ISSUE TITLE
ProGuard

### ISSUE THREAD

**Issue by alexwillingham** [pacify-io/pacifysdk-android-sample#1]
Add a minimal and sufficient ProGuard configuration to the sample for release mode, so that SDK users may refer to it.

**Comment by AleksIakushev** [comment]
I'm able to reproduce issue with no plans here, also I have found a solution:
adding following line into proguard-rules.pro
-keep public class com.masslight.pacify.framework.core.model.** { *; }

**Comment by alexwillingham** [comment]
Done
